name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      
    - name: npm install
      run: npm install ./ui
      
    #- name: npm build1
    #  run: cd ui
    - name: npm build
      working-directory: ui
      run: npm run build
